version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.3
  linter: thekevjames/linter@1.0.36
commands:
  install: gcp-cli/install
  initialize: gcp-cli/initialize
  pre-commit: linter/pre-commit
jobs:
  style-check:
    docker:
      - image: python:3.7.6
    steps:
      - checkout
      - pre-commit
  test:
    docker:
      - image: python:3.7.6
    steps:
      - checkout
      - run:
          name: Install tox
          command: |
            pip install --progress-bar=off --user tox
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Run tox
          command: tox
      - save_cache:
          key: tested-deathnut-$CIRCLE_SHA1
          paths:
            - .tox/dist
  deploy:
    executor: gcp-cli/google
    steps:
      - install:
          version: 268.0.0
      - initialize
      - restore_cache:
          keys:
            - tested-deathnut-$CIRCLE_SHA1
      - run:
          name: Deploy artifact
          command: |
            ls -la .tox/dist/deathnut-0.1.zip
            gcs_folder="gs://deathnut/${CIRCLE_BRANCH}/"
            find .tox/dist -name *.zip -exec gsutil cp {} ${gcs_folder} \;
workflows:
  build_test_deploy:
    jobs:
      - style-check
      - test:
          requires:
            - style-check
      - deploy:
          requires:
            - test
