version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.3
commands:
  install: gcp-cli/install
jobs:
  # put precommit check here
  deploy:
    executor: gcp-cli/google
    steps:
      - install:
          version: 268.0.0
      - initialize
      - run: gcloud
workflows:
  build_test_deploy:
    jobs:
      - deploy

