version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.3
commands:
  install: gcp-cli/install
  initialize: gcp-cli/initialize
jobs:
  style-check:
    docker:
      - image: python:3.7.6
    steps:
      - checkout
      - run:
          name: pre-commit install
          command: pip install --progress-bar=off pre-commit
      - run:
          name: pre-commit run
          command: pre-commit run -a
  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install:
          version: 268.0.0
      - initialize
      - run:
          name: Install tox
          command: |
            apt-get install python-dev -y
            gcloud docker -a
            pip install -U pip
            pip install --user tox
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Run tox
          command: tox
      - save_cache:
          key: tested-deathnut-{{ .Revision }}
          paths:
            - .tox/dist
  deploy:
    executor: gcp-cli/google
    steps:
      - install:
          version: 268.0.0
      - initialize
      - restore_cache:
          keys:
            - tested-deathnut-{{ .Revision }}
      - run:
          name: Deploy artifact
          command: find .tox/dist -name *.zip -exec gsutil cp {} "gs://dist.getwellio.com/projects/deathnut/${CIRCLE_BRANCH}/" \;
workflows:
  build_test_deploy:
    jobs:
      - style-check
      - test:
          requires:
            - style-check
      - deploy:
          requires:
            - test
