version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.3
commands:
  install: gcp-cli/install
  initialize: gcp-cli/initialize
references:
  install_generate_openapi: &install_generate_openapi
    run:
      name: Install generate_openapi
      command: |
        gsutil cp gs://dist.getwellio.com/projects/master/generate-openapi-$GENERATE_OPENAPI_VERSION.zip ./generate-openapi.zip
        pip install --target=/home/circleci/project/test/e2e_tests/recipe-service generate-openapi.zip
  set_test_key: &set_test_key
    run:
      name: Set test key
      command: |
        echo "export GCLOUD_SERVICE_KEY=${GCLOUD_TEST_KEY}" >> $BASH_ENV
        echo ${GCLOUD_SERVICE_KEY} > ${HOME}/project/test/e2e_tests/recipe-service/keys/jwt-test.json
jobs:
  style-check:
    docker:
      - image: python:3.7.6
    steps:
      - checkout
      - run:
          name: pre-commit install
          command: pip install --progress-bar=off pre-commit
      - run:
          name: pre-commit run
          command: pre-commit run -a
  test:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      GENERATE_OPENAPI_VERSION: 1.0
    steps:
      - checkout
      - install:
          version: 268.0.0
      - initialize
      - *install_generate_openapi
      - run:
          name: Install tox
          command: |
            sudo apt-get install python-dev -y
            pyenv global 3.7.0 system
            gcloud docker -a
            pip install -U pip
            pip install --user tox
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - *set_test_key
      - run:
          name: Run tox
          command: tox
      - save_cache:
          key: tested-deathnut-{{ .Revision }}
          paths:
            - .tox/dist
  deploy:
    executor: gcp-cli/google
    steps:
      - install:
          version: 268.0.0
      - initialize
      - restore_cache:
          keys:
            - tested-deathnut-{{ .Revision }}
      - run:
          name: Deploy artifact
          command: find /home/circleci/project/.tox/dist -name *.zip -exec gsutil cp {} "gs://dist.getwellio.com/projects/deathnut/${CIRCLE_BRANCH}/" \;
workflows:
  build_test_deploy:
    jobs:
      - style-check
      - test:
          requires:
            - style-check
      - deploy:
          requires:
            - test
