version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.3
  linter: thekevjames/linter@1.0.36
commands:
  install: gcp-cli/install
  initialize: gcp-cli/initialize
  pre-commit: linter/pre-commit
jobs:
  pre-commit-check:
    docker:
      - image: python:3.7.6
    steps:
      - checkout
      - pre-commit
  test:
    docker:
      - image: python:3.7.6
    steps:
      - checkout
      - run:
          name: Install tox
          command: |
            pip install --progress-bar=off --user tox
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Run tox
          command: pwd && tox
  deploy:
    # restore cache from test step
    executor: gcp-cli/google
    steps:
      - install:
          version: 268.0.0
      - initialize
      - run: gcloud
workflows:
  build_test_deploy:
    jobs:
      - pre-commit-check
      - test:
          requires:
            - pre-commit-check
      - deploy:
          requires:
            - test
